language: objective-c
osx_image: xcode8.3
xcode_project: Optics.xcodeproj
xcode_scheme: Optics
xcode_sdk: iphonesimulator10.3

script:
  - xcodebuild clean build test -project "Optics.xcodeproj" -scheme "Optics" -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.3'

after_success:
  - bash <(curl -s https://codecov.io/bash)
